<?php
$active_group = 'dev';
$active_record = TRUE;
$db['dev']['username'] = 'user';
$db['dev']['password'] = 'pass';
$db['dev']['hostname'] = 'localhost';
$db['dev']['database'] = 'database';
$db['dev']['dbdriver'] = 'mysqli';
$db['dev']['dbprefix'] = '';
$db['dev']['pconnect'] = FALSE;
$db['dev']['db_debug'] = FALSE;
$db['dev']['cache_on'] = FALSE;
$db['dev']['cachedir'] = '';
$db['dev']['char_set'] = 'utf8';
$db['dev']['dbcollat'] = 'utf8_general_ci';

$db['live']['username'] = 'root';
$db['live']['password'] = 'pass';
$db['live']['hostname'] = 'localhost';
$db['live']['database'] = 'database';
$db['live']['dbdriver'] = 'mysqli';
$db['live']['dbprefix'] = '';
$db['live']['pconnect'] = FALSE;
$db['live']['db_debug'] = FALSE;
$db['live']['cache_on'] = FALSE;
$db['live']['cachedir'] = '';
$db['live']['char_set'] = 'utf8';
$db['live']['dbcollat'] = 'utf8_general_ci';



/* Autogenerated Configuration for db 2012-01-06 */
