<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="description" content="business cloud services" />
		<meta name="keywords" content="business, could, voip, business cloud services, group, todo, task, project management, group collaboration, task management, file storage, file sync, group sharing, group messaging" />
		<title>iGroups | business cloud services</title>
		<link rel="icon" type="image/ico" href="favicon.ico">
		<link href="/assets/themes/homepage/css/homepage.css" rel="stylesheet" type="text/css">
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-26105028-1']);
		  _gaq.push(['_setDomainName', 'igrou.ps']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
	</head>
	<body>
		<div id="page">
			<br><br>
			<h1><a href="https://www.igrou.ps">iGroups</a> Terms of Service</h1>
			<p>
				THESE TERMS OF SERVICE (the AGREEMENT) GOVERNS YOUR USE OF OUR SERVICES, WHETHER CHARGEABLE OR NOT, as available to you through www.igrou.ps (the "Website"), which is owned, maintained and operated by iGroups Inc., a private company incorporated in the U.S. ("iGroups, Inc.")<br>
				<br>
				YOU SIGNIFY YOUR ASSENT TO THIS AGREEMENT BY CLICKING A BOX INDICATING YOUR ACCEPTANCE OF THIS AGREEMENT OR BY ACTUALLY USING THE SERVICES PROVIDED THROUGH THE WEBSITE. IF YOU DO NOT AGREE WITH THE TERMS AND CONDITIONS SET FORTH HEREIN, YOU MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE THE SERVICES.<br>
				<br>
				IF YOU ARE ENTERING INTO THIS AGREEMENT ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THIS AGREEMENT, IN WHICH CASE THE TERMS "YOU" OR "YOUR" SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT HAVE SUCH AUTHORITY, YOU MUST NOT ACCEPT THIS AGREEMENT ON THEIR BEHALF.<br>
				<br>
				the U.S.e of certain Services may be subject to additional terms and conditions in respect with such Services. Certain additional terms are set forth in Appendix A attached hereto. Unless otherwise provided by the additional terms and conditions applicable to the Services in which you choose to participate (the "Additional Terms"), those Additional Terms are hereby incorporated into this Agreement as an integral part hereof. In the event of a conflict between this Agreement and the Additional Terms, the Additional Terms shall prevail. NOTE that omission of a Partner and/or its Services Additional Terms, shall not release you from complying with any of Partner's Additional Terms relating to the U.S.e of Services by You.<br>
				<br>
				iGroups may modify this Agreement from time to time and such modification shall be effective upon posting by on the Website. You agree to be bound to any changes to this Agreement when you use the Services after any such modification is posted. It is therefore important that you review this Agreement regularly upon each use of the Services to ensure you are updated as to any changes.<br>
				<br>
				You may not access the Services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.<br>
				<br>
				1. DEFINITIONS. <br>
				1.1. "Affiliate" means any entity which directly or indirectly controls, is controlled by, or is under common control with the subject entity. "Control," for purposes of this definition, means direct or indirect ownership or control of more than 50% of the voting interests of the subject entity. <br>
				1.2. "Content" has the meaning ascribed to it in Section 6.1 bellow. <br>
				1.3. "Malicious Code" means viruses, worms, time bombs, Trojan horses and other harmful or malicious code, files, scripts, agents or programs. <br>
				1.4. "Third Party Services" means online applications, tools, services and offline software products that are provided by Partners, which may, or may not, be identified as such, and that are offered to you through the Website, whether interoperate with the Services provided solely by iGroups or not. <br>
				1.5. "Order Form" means the documents for placing orders hereunder or any other manner by which You accessed to the Services, whether submitted online or otherwise, including any addenda or amendment thereto, that are entered into between You and iGroups or any of our Partners from time to time. By entering into an Order Form hereunder, you agree to be bound by the terms of this Agreement as if it were an original party hereto. Order Forms shall be deemed incorporated herein by reference. <br>
				1.6. "Partner" entities and/or individuals other than iGroups, which are providing Services through the Website, whether interoperate with the Services provided solely by iGroups or not. The list of Partners and certain Additional Terms attached hereto as Appendix A, which will be updated from time to time by iGroups, at its sole discretion. <br>
				1.7. "Premium Services" means Services that you or Your Affiliates purchase under an Order Form, as distinguished from Services provided through the Website, free of charge. <br>
				1.8. "Services" means the products, modules, tools and services, whether chargeable or not, that are ordered by You and/or made available, from time to time, by iGroups online via the Website and/or other web pages designated by iGroups, including, without limitation, Third Party Services. <br>
				1.9. "You" or "Your" means the company or other legal entity for which you are accepting this Agreement, and Affiliates of that company or entity.<br>
				<br>
				2. ELIGIBILITY <br>
				Use of the Services is void where prohibited. By using the Services, You represent and warrant that (a) all registration information You submit is truthful and accurate; (b) You will maintain the accuracy of such information; (c) You are 18 years of age or older; and (d) Your use of the Services does not violate any applicable law or regulation. Your profile may be deleted and your registration as a member with the Website may be terminated without warning, if iGroups believe that you are less than 18 years of age. By using the Premium Services, You declare and represents that You are more than 18 years of age and that You have full legal capacity to complete such contractual action, including the U.S.e of a credit card or use of any other method of payment, without need in any additional approvals or consents.<br>
				<br>
				3. THE SERVICES <br>
				3.1. The Provision of the Services by iGroups <br>
				3.1.1.	This Agreement grants you the possibility of using of the software of iGroups via Internet as Software as a Service ("SaaS") for the term of this Agreement. <br>
				3.1.2.	iGroups is constantly innovating in order to provide the best possible experience for its users. You acknowledge and agree that the form and nature of the Services, which iGroups provides, may change from time to time without prior notice to you. <br>
				3.1.3.	As part of this continuing innovation, you acknowledge and agree that iGroups may stop (permanently or temporarily) providing the Services (or any features within the Services) to you or to users generally at iGroups' sole discretion, without prior notice to You. You may stop using the Services at any time. You acknowledge that iGroups may replace its Partners, which provide the Third Party Services at any time, and from time to time, at its sole discretion, without obtaining You consent. <br>
				3.1.4.	You acknowledge and agree that if iGroups disables access to Your account, You may be prevented from accessing the Services, Your account details or any files or other content which is contained in Your account, hence, iGroups strongly recommends that You store any content You insert into the Services as any time You access to the Services. <br>
				3.1.5.	You acknowledge and agree that while iGroups may not currently have set a fixed upper limit on the amount of storage space used for the provision of any Service, such fixed upper limits may be set by iGroups at any time, at iGroups' discretion. <br>
				3.2. Availability of the Services. While iGroups will make all reasonable efforts to ensure that the Services are available at all times, iGroups does not guarantee, represent or warrant that Your access to any of the Services will be uninterrupted or error-free. In addition, while iGroups makes reasonable efforts to ensure that all content and/or information submitted by You to iGroups will be secure, iGroups does not guarantee that the Services will be free from loss, corruption, attack, viruses, worms, trojan horses or other harmful components, or from interference, hacking or other security intrusions. You should be sure to back up your own system periodically to ensure that all content is available to you in the event of any loss or damage. iGroups may change, suspend or discontinue any of the Services at any time. iGroups may also impose limits on the U.S.e of or access to certain features or portions of the Services, in any case without notice or liability.<br>
				<br>
				4. USE OF THE SERVICES BY YOU <br>
				4.1. In order to access certain Services, You may be required to provide information about Yourself (such as identification or contact details) as part of the registration process for the Service, or as part of Your continued use of the Services. You agree that any registration information You give to iGroups will always be accurate, correct and up to date. <br>
				4.2. You agree to use the Services only for purposes that are permitted by (a) this Agreement; and (b) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions (including any laws regarding the export of data or software). <br>
				4.3. You agree not to access (or attempt to access) any of the Services by any means other than through the interface that is provided by iGroups, unless you have been specifically allowed to do so in a separate agreement with iGroups. You specifically agree not to access (or attempt to access) any of the Services through any automated means (including use of scripts or web crawlers). <br>
				4.4. You agree that You will not engage in any activity that interferes with or disrupts the Services (or the servers and networks which are connected to the Services). <br>
				4.5. Unless You have been specifically permitted to do so in a separate written agreement with iGroups, You agree that You will not reproduce, duplicate, copy, sell, trade or resell the Services for any purpose. <br>
				4.6. You agree that You are solely responsible for (and that iGroups has no responsibility to You or to any third party for) any breach of Your obligations under this Agreement and for the consequences (including any loss or damage which iGroups may suffer) of any such breach.<br>
				<br>
				5. FEES AND PAYMENT FOR PREMIUM SERVICES <br>
				5.1. The Premium Services offered on the Website require payment of fees. If you elect to sign up for Premium Services, You shall pay all applicable fees, as described on the Website in connection with such Premium Services selected by You. iGroups reserves the right to change its prices and at any time. You authorize iGroups directly or through third parties, to make any inquiries it considers necessary to validate Your account and financial information as provided while signing up for such Services. <br>
				5.2. The fees for the Premium Services shall be paid as follows (unless instructed otherwise in the terms attached to any such Premium Services):<br>
				<br>
				A.	Pay As You Go ("PAYG") You will be required to either provide the company with your credit card number and other relevant information that will enable iGroups to charge it, or provide iGroups with your PayPal account or any other method of payment, in order for iGroups to charge You for the Premium Services, at any time upon purchase of Premium Services by You, all in accordance with the prices and timing of payment as shall be provided in the Website; or <br>
				<br>
				B.	Recurring Charge ("Recurring Charge Plans") - The payment shall be made in accordance with the Recurring Charge Plans described in the Website. A member of one of the Recurring Charge Plans will provide his/her/its credit card number and any relevant information thereto and the relevant fees shall be charged automatically in accordance with the payment timing as detailed in the relevant Recurring Charge Plan. At each Recurring Charge Plan, You will be entitled to receive iGroups' credit as described in the details of the recurring charge in the website (for demonstration purposes only, a recurring charge of $ 10 may entitle You to receive an additional $ 10 in iGroups credit) per month (the "iGroups Credit"). The iGroups Credit shall be added to Your total credit in the Website to be used for purchasing Premium Services. If iGroups does not receive a written request for termination of a Recurring Charge Plan to one of the addresses listed in Section 19 below, You acknowledge and understand that iGroups will continue to charge You for the Premium Services as long as Your account remains active regardless if the Premium Services are used or not. The Recurring Charge Plans may be amended from time to time and may be subject to additional terms. Any payment of fees made out of Your Website credit shall be first deducted from the iGroups Credit and only thereafter from the charged funds. The iGroups Credit is NON-REFUNDABLE!<br>
				<br>
				5.3. You will provide iGroups with valid and updated credit card information, or with a valid purchase order or alternative document reasonably acceptable to iGroups. If You provide credit card information to iGroups, You authorize iGroups to charge such credit card for all Services purchased by You through the Website. <br>
				5.4. If any amount owing by You under this Agreement or any other agreement for any Services is 30 or more days overdue (or 10 or more days overdue in the case of amounts You have authorized iGroups to charge Your credit card), iGroups may, without limiting iGroups' other rights and remedies, accelerate Your unpaid fee obligations under such agreements so that all such obligations become immediately due and payable, and suspend Your access to the Services until such amounts are paid in full. We will give You at least 3 days prior notice that Your account is overdue, before suspending Services to You. <br>
				5.5. Unless otherwise stated, the fees do not include any taxes, levies, duties or similar governmental assessments of any nature, including but not limited to value-added, sales, use or withholding taxes, assessable by any local, state, provincial, federal or foreign jurisdiction (collectively, "Taxes"). You are responsible for paying any and all Taxes associated with Your purchases hereunder. If iGroups have the legal obligation to pay or collect Taxes for which You are responsible under this paragraph, the appropriate amount shall be invoiced to and paid by You, unless You provide iGroups with a valid tax exemption certificate authorized by the appropriate taxing authority. For greater clarity, iGroups is solely responsible for taxes assessable against it based on iGroups' income, property and employees. <br>
				5.6. iGroups reserves the right to change the fees and to charge for use of Services that are currently available free of charge. You will not be charged for using any Services, unless You have opted for any of the payment methods listed above.<br>
				<br>
				6. CONTENT IN THE SERVICES <br>
				6.1. You understand that all information (such as data files, written text, computer software, music, audio files or other sounds, photographs, videos or other images), formation, designing, storage, management, sharing and linking of media and/or document files (including, but not limited to user comments, messages, information, data, graphics, photographs, images, illustrations, animations, software, audio and video), which You may have access to as part of, or through Your use of, the Services are the sole responsibility of the person from which such content originated. All such information is referred to below as the Content. <br>
				6.2. You should be aware that Content presented to You as part of the Services, including but not limited to advertisements in the Services and sponsored Content within the Services may be protected by intellectual property rights which are owned by the sponsors or advertisers who provide that Content to iGroups (or by other persons or companies on their behalf). You may not modify, rent, lease, loan, sell, distribute or create derivative works based on this Content (either in whole or in part) unless You have been specifically told that You may do so by iGroups or by the owners of that Content, in a separate written agreement. <br>
				6.3. iGroups reserves the right (but not the obligation) to pre-screen, review, flag, filter, modify, refuse or remove any or all Content from any Service. In addition, there are commercially available services and software to limit access to material that You may find objectionable. <br>
				6.4. You understand that by using the Services You may be exposed to Content that You may find offensive, indecent or objectionable and that, in this respect, You use the Services at Your own risk. <br>
				6.5. You agree that You are solely responsible for (and that iGroups has no responsibility to You or to any third party for) any Content that You create, transmit or display while using the Services and for the consequences of Your actions (including any loss or damage which iGroups may suffer) by doing so.<br>
				<br>
				7. CONTENT LICENSE FROM YOU <br>
				7.1. You retain copyright and any other rights You already hold in Content which You submit, post or display on or through, the Services. By submitting, posting or displaying non-confidential Content (as apposed to confidential Content), You give iGroups a perpetual, irrevocable, worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display and distribute any non-confidential Content which You submit, post or display on or through, the Services. This license is for the sole purpose of enabling iGroups to display, distribute and promote the Services and may be revoked for certain Services as defined in the Additional Terms of such Services. 'non-confidential Content' is referred to Content submitted by you which is not marked or clearly identified in any way as confidential, or Content which You make available to the public, through the Website such as blogs, posts etc. <br>
				7.2. You agree that this license includes a right for iGroups to make such Content available to other companies, organizations or individuals with whom iGroups has relationships for the provision of syndicated services, and to use such Content in connection with the provision of those services. <br>
				7.3. You understand that iGroups, in performing the required technical steps to provide the Services to our users, may (a) transmit or distribute Your Content over various public networks and in various media; and (b) make such changes to Your Content as are necessary to conform and adapt that Content to the technical requirements of connecting networks, devices, services or media. You agree that this license shall permit iGroups to take these actions. <br>
				7.4. You confirm and warrant to iGroups that You have all the rights, power and authority necessary to grant the above license.<br>
				<br>
				8. OTHER CONTENT <br>
				8.1. The Services may include hyperlinks to other web sites or content or resources. iGroups may have no control over any web sites or resources which are provided by companies or persons other than iGroups. <br>
				8.2. You acknowledge and agree that iGroups is not responsible for the availability of any such external sites or resources, and does not endorse any advertising, products or other materials on or available from such web sites or resources. <br>
				8.3. You acknowledge and agree that iGroups is not liable for any loss or damage which may be incurred by You as a result of the availability of those external sites or resources, or as a result of any reliance placed by You on the completeness, accuracy or existence of any advertising, products or other materials on, or available from, such web sites or resources. <br>
				8.4. The Website may incorporate certain functionality that allows, via the system or network of which the Website is a component, the routing and transmission of, and online access to, certain digital communications and content made available by third parties (Third Party Content). By using such Website functionality, You acknowledge and agree that You are directing iGroups to access and transmit to You Third Party Content associated with such functionality. Because iGroups does not control Third Party Content, You agree that iGroups is neither responsible nor liable for any Third Party Content, including the accuracy, integrity, quality, legality, usefulness, or safety of, or intellectual property rights relating to, Third Party Content. iGroups has no obligation to monitor Third Party Content, and iGroups may block or disable access to any Third Party Content (in whole or part) via the Website at any time. Your access to or receipt of Third Party Content via the Website does not imply iGroups' endorsement of, or iGroups' affiliation with any provider of, such Third Party Content. Further, Your use of Third Party Content may be governed by additional terms and conditions that are not set forth in this Agreement or iGroups' Privacy Policy (for example, terms and conditions that are made available by the providers of such Third Party Content). This Agreement does not create any legal relationship between You and the providers of such Third Party Content with respect to such Third Party Content, and nothing in this Agreement shall be deemed to be a representation or warranty by iGroups, or any of iGroups' Affiliates, or respective representatives or providers, with respect to any Third Party Content.<br>
				<br>
				9. THIRD PARTY SERVICES. <br>
				The Website may include Third Party Services. Because iGroups does not control Third Party Services, You agree that neither iGroups nor iGroups' Affiliates, nor iGroups' respective representatives, are responsible or liable for any Third Party Services, including the performance, accuracy, integrity, quality, legality, usefulness, or safety of, or intellectual property rights relating to, Third Party Services or their use. iGroups has no obligation to monitor Third Party Services, and it may remove or restrict access to any Third Party Services (in whole or part) from the Website at any time. The availability of Third Party Services on the Website does not imply iGroups' endorsement of, or iGroups' affiliation with any provider of, such Third Party Services. Further, Your use of Third Party Services may be governed by additional terms and conditions that are not set forth in this Agreement or iGroups' Privacy Policy (for example, terms and conditions that are made available by the providers themselves in connection with Third Party Services). This Agreement does not create any legal relationship between You and providers of a Third Party Services with respect to Third Party Services, and nothing in this Agreement shall be deemed to be a representation or warranty by iGroups, or any of iGroups' Affiliates, or iGroups ' respective representatives or providers, with respect to any Third Party Service. iGroups suggests that you consult your legal advisor before filing a notice or counter-notice.<br>
				<br>
				10.	USE OF COMMUNICATION SERVICES <br>
				The Website may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication facilities designed to enable You to communicate with the public at large or with a group (collectively, "Communication Services"), You agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service. By way of example, and not as a limitation, You agree that when using a Communication Service, You will not: <br>
				10.1. Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others. <br>
				10.2. Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information. <br>
				10.3. Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless You own or control the rights thereto or have received all necessary consents. <br>
				10.4. Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another's computer. <br>
				10.5. Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages. <br>
				10.6. Conduct or forward surveys, contests, pyramid schemes or chain letters. <br>
				10.7. Download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner. <br>
				10.8. Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded. <br>
				10.9. Restrict or inhibit any other user from using and enjoying the Communication Services. <br>
				10.10. Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service. <br>
				10.11. Harvest or otherwise collect information about others, including e-mail addresses, without their consent. <br>
				10.12. Violate any applicable laws or regulations.<br>
				<br>
				iGroups has no obligation to monitor the Communication Services. However, iGroups reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. iGroups reserves the right to terminate Your access to any or all of the Communication Services at any time without notice for any reason whatsoever.<br>
				<br>
				iGroups reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in iGroups sole discretion.<br>
				<br>
				Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you download the materials<br>
				<br>
				11.	DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY <br>
				11.1. YOU EXPRESSLY AGREE THAT YOUR USE OF, OR INABILITY TO USE, THE SERVICES IS AT YOUR SOLE RISK. SERVICES AND ANY PRODUCTS ORDERED, OR USED, BY YOU THROUGH THE SERVICES ARE (EXCEPT AS EXPRESSLY STATED IN WRITING BY iGroups) PROVIDED AS IS AND AS AVAILABLE FOR YOUR USE, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, THE ABOVE EXCLUSION OF IMPLIED WARRANTIES MAY NOT APPLY TO YOU. <br>
				11.2. PLEASE KEEP IN MIND THAT SOME OF THE CONTENT THAT WE MAKE AVAILABLE TO YOU THROUGH TH SERVICES COMES FROM PARTNERS OR ANY OTHER THIRD PARTY WEB SERVICES. ALL SUCH CONTENT IS PROVIDED TO YOU AS IS, AS-AVAILABLE BASIS AND iGroups, THE PARTNERS AND OTHER THIRD PARTY LICENSORS, DO NOT MAKE AND HEREBY DISCLAIMS AND WARRANTY, EXPRESS OR IMPLIED, WITH RESPECT TO TGE CONTENT, INCLUDING, BUT NOT LIMITED TO, THE ACCURACY, COMPLETENESS, TIMELINESS, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OF THE CONTENT OR OF THE MEDIA ON WHICH THE CONTENT IS PROVIDED. THE CONTENT AND YOUR USE OF IT ARE SUBJECT TO CHANGE AND/OR REMOVAL AT ANY TIME. <br>
				11.3. IN NO CASE SHALL iGroups, ITS AFFILIATES, PARTNERS, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS OR CONTRACTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF ANY OF THE SERVICES OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR USE OF THE SERVICES. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH JURISDICTIONS, iGroups LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY APPLICABLE LOCAL LAW. <br>
				11.4. WITHOUT LIMITING THE FOREGOING, IN PARTICULAR, iGroups, ITS AFFILIATES, PARTNERS, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS OR CONTRACTORS, AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT: <br>
				<br>
				A. YOUR USE OF THE SERVICES WILL MEET YOUR REQUIREMENTS, <br>
				B. YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, <br>
				C. ANY INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, AND <br>
				D. DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO YOU AS PART OF THE SERVICES WILL BE CORRECTED. <br>
				<br>
				11.5. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH the U.S.E OF THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. <br>
				11.6. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM iGroups OR THROUGH OR FROM THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS. <br>
				11.7. WITHOUT LIMITING THE GENERALITY OF SECTIONS 11.1 AND 11.3 ABOVE, YOU EXPRESSLY UNDERSTAND AND AGREE THAT iGroups, ITS AFFILIATES, PARTNERS, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS OR CONTRACTORS, AND ITS LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY LOSS OR DAMAGE WHICH MAY BE INCURRED BY YOU, INCLUDING BUT NOT LIMITED TO LOSS OR DAMAGE AS A RESULT OF: <br>
				<br>
				A. ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY CONTENT, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY THIRD PARTY WHOSE ADVERTISING, SERVICES OR CONTENT APPEARS ON THE SERVICES; <br>
				B. ANY CHANGES WHICH iGroups MAY MAKE TO THE SERVICES, OR FOR ANY PERMANENT OR TEMPORARY CESSATION IN THE PROVISION OF THE SERVICES (OR ANY FEATURES WITHIN THE SERVICES); <br>
				C.	THE DELETION OF, CORRUPTION OF, OR FAILURE TO STORE, ANY CONTENT AND OTHER COMMUNICATIONS DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE SERVICES; <br>
				D. YOUR FAILURE TO PROVIDE iGroups WITH ACCURATE ACCOUNT INFORMATION; <br>
				E. YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL; <br>
				<br>
				11.8. THE LIMITATIONS ON iGroups AND PARTNERS LIABILITY TO YOU IN THIS SECTION 11 ABOVE SHALL APPLY WHETHER OR NOT iGroups HAS BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.<br>
				<br>
				12.	PROPRIETARY RIGHTS <br>
				12.1. You acknowledge and agree that iGroups (or iGroups' licensors) own all legal right, title and interest in and to the Services, including any intellectual property rights which subsist in the Services (whether those rights happen to be registered or not, and wherever in the world those rights may exist). You further acknowledge that the Services may contain information which is designated confidential by iGroups and that You shall not disclose such information without iGroups' prior written consent. <br>
				12.2. Unless You have agreed otherwise in writing with iGroups, nothing in this Agreement gives You a right to use any of iGroups' trade names, trade marks, service marks, logos, domain names, and other distinctive brand features. <br>
				12.3. Other than the limited license set forth in Section 13, iGroups acknowledges and agrees that it obtains no right, title or interest from You (or Your licensors) under This Agreement in or to any Content that You submit, post, transmit or display on, or through, the Services, including any intellectual property rights which subsist in that Content (whether those rights happen to be registered or not, and wherever in the world those rights may exist). Unless You have agreed otherwise in writing with iGroups, you agree that You are responsible for protecting and enforcing those rights and that iGroups has no obligation to do so on your behalf. <br>
				12.4. You agree that You shall not remove, obscure, or alter any proprietary rights notices (including copyright and trade mark notices) which may be affixed to or contained within the Services. <br>
				12.5. Unless You have been expressly authorized to do so in writing by iGroups, you agree that in using the Services, You will not use any trade mark, service mark, trade name, logo of any company or organization in a way that is likely or intended to cause confusion about the owner or authorized user of such marks, names or logos.<br>
				<br>
				14.	SOFTWARE UPDATES The Software which You use may automatically be updated from time to time by iGroups. These updates are designed to improve, enhance and further develop the Services and may take the form of bug fixes, enhanced functions, new software modules and completely new versions. You agree to receive such updates (and permit iGroups to deliver these to you) as part of your use of the Services.<br>
				<br>
				15.	INDEMNIFICATION You agree to defend, indemnify and hold harmless iGroups, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) Your use of and access to the Website and/or the Services; (ii) Your violation of any term of this Agreement; (iii) Your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that one of Your content/data caused damage to a third party. This defense and indemnification obligation will survive he termination of the Services and of this Agreement.<br>
				<br>
				16.	TERM AND TERMINATION <br>
				16.1. This Agreement commences on the date You accept it and continues until terminated according to the provisions below. <br>
				16.2. SohohOS reserves the right, upon its sole discretion and at any time, to prevent or restrict Your use of the Website and the Services, for any reason whatsoever, without prior notice and without iGroups being liable toward You and toward any third party. <br>
				16.3. Without derogating from the generality of the above, if and when, upon submitting an Order Form through the Website, You provide incorrect identifying details, including address, identification number, credit card details - in relation to the Services, etc. - and/or where You choose to pay by credit card and the application is rejected by the credit company and You fail to take action within three (3) days of receiving such rejection from the credit company in order to resolve the problem and obtain a new approval from the credit company, iGroups shall be entitled to close Your user account upon its sole discretion, without derogating from its right to collect the payments due from You and/or any other remedy to which it shall be entitled by law. <br>
				16.4. iGroups may terminate this Agreement, Your account and the Services for any reason upon 10 days written notice to You. Subject to any Additional Terms applicable to a certain Service, You may terminate this Agreement, Your account and any of the Services at any time. Such termination shall be made on the Website and according to the instructions posted therein. The date and time of such termination of this Agreement, Your account and any of the Services shall be within three (3) days following the date and time on which You have completed the cancellation process on the Website. <br>
				16.5. Upon any termination by iGroups, You shall pay any unpaid fees covering the remainder of the term of all Order Forms after the effective date of termination. In no event shall any termination relieve You of the obligation to pay any fees payable to iGroups for the period prior to the effective date of termination. <br>
				16.6. You shall have the sole responsibility to back-up Your Content or any other data in comma separated value (.csv) format (or any other applicable format) along with attachments. iGroups shall have no obligation to maintain or provide any of Your data/Content and upon termination of the Services, iGroups may, in its sole discretion and unless legally prohibited, delete all of Your data/Content in iGroups' systems or otherwise in iGroups' possession or under iGroups' control. <br>
				16.7. Section 1 (Definitions), 5 (Fees and Payment for Purchased Services; in case of overdue payment) 11 (Disclaimer of Warranties; Limitation of Liability), 12, 15 (Indemnification), 16 (Term and Termination) and 17 (Refunds) and 21 (General), shall survive any termination or expiration of this Agreement.<br>
				<br>
				17.	REFUNDS <br>
				Subject to any applicable Additional Terms, in the event of termination of this Agreement and all of the Services (used by you), You will be refunded the remaining portion of fees not used prior to the termination of this Agreement and the Services in accordance with the Refund Policy: iGroups offers a 14-day refund guaranty ("Guaranty Period"). In case of termination of this Agreement and all of the Services which You have acquired, You can submit a refund request by email to info@igrou.ps within the Guaranty Period in order to receive the refund of the remaining unused portion of fees. iGroups will not refund any amounts paid after the elapse of the Guaranty Period.<br>
				<br>
				18.	BETA TEST WARNING <br>
				Please note that the Website is currently in its BETA version and undergoing BETA testing. You understand and agree that the Services may still contain software bugs, suffer disruptions and not operate as intended or designated. Your use of the Services at this stage signifies your understanding of and agreement to participate in the Service BETA testing.<br>
				<br>
				19.	INFORMATION OR COMPLAINTS. If you have a question or complaint regarding the Website, please feel free to contact us via e-mail at info@igrou.ps E-mail communications are not necessarily secure, so please do not include credit card information or other sensitive information in any e-mail to us. You may also contact us by writing to us at: <br>
				<br>
				iGroups, Inc. <br>
				86 Saint Botolph St, #10<br>
				Boston, MA 02116<br>
				USA<br>
				<br>
				20.	CLAIMS OF COPYRIGHT INFRINGEMENT. <br>
				20.1. In the United States, the Digital Millennium Copyright Act of 1998 (the DMCA) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. Other protections for copyright owners are available in other jurisdictions. If you believe in good faith that materials available on the Website infringe Your copyright, You (or Your agent) may send iGroups a notice requesting iGroups to remove the material or disable access to it. If You believe in good faith that someone has wrongly filed a notice of copyright infringement against You, please send iGroups a counter-notice. In the United States, notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA (see http://www.copyright.gov for details). In addition, notices should include: Your contact details, the full bibliographic details of the material, the exact and full URL where You found the material, proof that You are the rights holder and a statement that, under penalty of perjury, You are the rights holder or are an authorized representative. <br>
				20.2. Upon receipt of notification the Notice and Takedown procedure is then invoked as follows: (a) iGroups will acknowledge receipt of Your complaint and will make an initial assessment of the validity and plausibility of the complaint; (b) upon receipt of a valid complaint the material will be temporarily removed from the website pending an agreed solution; (c) e will contact the contributor who deposited the material, if relevant, and the contributor will be notified that the material is subject to a complaint, under what allegations, and will be encouraged to assuage the complaints concerned; (d) the complainant and the contributor will be encouraged to resolve the issue swiftly and amicably and to the satisfaction of both parties, and the material is replaced on the website unchanged or with changes, or is permanently removed. If the contributor and the complainant are unable to agree a solution, the material will remain unavailable through the Website until a time when a resolution has been reached. <br>
				<br>
				Notices and counter-notices should be sent to: <br>
				<br>
				via registered mail<br>
				iGroups, Inc. <br>
				86 Saint Botolph St, #10<br>
				Boston, MA 02116<br>
				USA<br>
				<br>
				Via e-mail: <br>
				info@igrou.ps<br>
				<br>
				21.	GENERAL <br>
				21.1. Assignment. Neither party may assign any of its rights or obligations hereunder, whether by operation of law or otherwise, without the prior written consent of the other party (not to be unreasonably withheld). Notwithstanding the foregoing, iGroups may assign this Agreement in its entirety (including all Order Forms), without Your consent, to its Affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets. A party's sole remedy for any purported assignment by the other party in breach of this paragraph shall be, at the non-assigning party's election, termination of this Agreement upon written notice to the assigning party. <br>
				21.2. Entire Agreement. This Agreement, the Privacy Policy and any other Additional Terms of Services or of the Website posted by iGroups, including all exhibits and addenda hereto and all Order Forms, constitutes the entire agreement between the parties and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter. <br>
				21.3. You agree that: (i) the Website shall be deemed solely based in the U.S.; and (ii) the Website shall be deemed a passive website that does not give rise to personal jurisdiction over iGroups, either specific or general, in jurisdictions other than the U.S. This Agreement shall be governed by the internal substantive laws of the U.S., without respect to its conflict of laws principles. Any claim or dispute between You and iGroups that arises in whole or in part from the Website and/or the Services shall be decided exclusively by a court of competent jurisdiction located in Boston, Massachusetts. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and iGroups' failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND iGroups AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE WEBSITE AND/OR THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION SHALL BE PERMANENTLY BARRED. <br>
				<br>
				By registering to the Website and providing Your email address, You expressly agree to receive promotional content from iGroups, by email, from time to time. If You provide iGroups with Your phone number (at any stage of use of the Services), iGroups shall be entitled to send You promotional SMS notices from time to time. If You wish not to receive such promotional content / notices, You may notify iGroups at any time.
			</p>

		</div>

		<div id="footer">
			<div class="nav">
				<a title="follow us on twitter" href="http://www.twitter.com/igroups">@twitter</a>
				<a title="follow us on facebook" href="http://www.facebook.com/igroups">@facebook</a>
				<a title="contact us" href="mailto:support@igrou.ps">contact us</a>
			</div>
			<p style="padding-top: 8px; padding-left: 10px; font-size:13px">iGroups, Inc is a Boston-based company. We make cool things.</p>
		</div>
		
		
		
		
	</body>
</html>

